# Generated by Django 4.2.1 on 2023-05-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_initial'),
        ('objects', '0002_remove_cart_clothes_remove_favorite_clothes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='clothing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.traditionalclothing'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='food',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.traditionalfood'),
        ),
    ]
