# Generated by Django 4.2.1 on 2023-05-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traditionalclothing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.category'),
        ),
    ]
